# -*- coding: utf-8 -*-
"""Esto AI/ML challenge

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rDWnwWkqW-6OBl7HN42H72zJoNd73E33
"""

import pandas as pd
df = pd.read_csv('esto_challenge_data.csv')

df

X = df.drop(columns = 'high_risk')
Y = df['high_risk']

from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size= 0.3, stratify = Y )

Y_test.value_counts()

Y_train.value_counts()

from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(max_depth=18, n_estimators= 160)

clf.fit(X_train, Y_train)

clf.score(X_test, Y_test)

from sklearn.metrics import roc_auc_score, f1_score, classification_report
from sklearn.model_selection import KFold
import numpy as np
kf = KFold(n_splits=5, shuffle=True, random_state=42)

roc_auc_scores = []
f1_scores = []

for train_idx, val_idx in kf.split(X_train):
    X_tr, X_val = X_train.iloc[train_idx], X_train.iloc[val_idx]
    y_tr, y_val = Y_train.iloc[train_idx], Y_train.iloc[val_idx]

    clf.fit(X_tr, y_tr)
    preds = clf.predict(X_val)
    probs = clf.predict_proba(X_val)[:, 1]

    roc_auc_scores.append(roc_auc_score(y_val, probs))
    f1_scores.append(f1_score(y_val, preds))

print("Average ROC-AUC (5-fold):", np.mean(roc_auc_scores))
print("Average F1-Score (5-fold):", np.mean(f1_scores))

y_pred = clf.predict(X_test)
y_prob = clf.predict_proba(X_test)[:, 1]

print("\nTest ROC-AUC:", roc_auc_score(Y_test, y_prob))
print("Test F1-Score:", f1_score(Y_test, y_pred))
print("\nClassification Report:\n", classification_report(Y_test, y_pred))

import matplotlib.pyplot as plt
importances = pd.Series(clf.feature_importances_, index=X.columns)
top_features = importances.sort_values(ascending=False).head(10)

plt.figure(figsize=(8,5))
top_features.plot(kind='barh')
plt.title("Top 10 Feature Importances")
plt.gca().invert_yaxis()
plt.show()

